//! Generic, string-addressable parameter tables.
//!
//! [`param_table!`] turns a plain `Copy` struct into a flat list of named, ranged parameters
//! (`"filter/cutoff_hz"`, …) with `get`/`set` by id. Engine bindings use the [`Params`]
//! trait to build inspectors and `set_param` APIs without knowing the concrete struct.

/// How a parameter should be presented and validated.
#[derive(Clone, Copy, Debug, PartialEq)]
pub enum ParamKind {
    Float { min: f32, max: f32, step: f32 },
    /// Like `Float` but with an exponential (logarithmic) slider, e.g. frequencies.
    Exp { min: f32, max: f32 },
    Int { min: i32, max: i32 },
    Enum(&'static [&'static str]),
}

impl ParamKind {
    pub fn clamp(&self, v: f32) -> f32 {
        match *self {
            ParamKind::Float { min, max, .. } | ParamKind::Exp { min, max } => v.clamp(min, max),
            ParamKind::Int { min, max } => v.round().clamp(min as f32, max as f32),
            ParamKind::Enum(names) => v.round().clamp(0.0, (names.len() - 1) as f32),
        }
    }
}

/// Values that can round-trip through an `f32` for the generic get/set API.
pub trait ParamValue: Copy {
    fn to_f32(self) -> f32;
    fn from_f32(v: f32) -> Self;
}

impl ParamValue for f32 {
    fn to_f32(self) -> f32 {
        self
    }
    fn from_f32(v: f32) -> Self {
        v
    }
}

impl ParamValue for u8 {
    fn to_f32(self) -> f32 {
        self as f32
    }
    fn from_f32(v: f32) -> Self {
        v.round().clamp(0.0, 255.0) as u8
    }
}

impl ParamValue for bool {
    fn to_f32(self) -> f32 {
        if self {
            1.0
        } else {
            0.0
        }
    }
    fn from_f32(v: f32) -> Self {
        v >= 0.5
    }
}

/// Implements [`ParamValue`] for a `#[repr(u8)]` enum that has `from_index`.
macro_rules! impl_param_value_enum {
    ($t:ty) => {
        impl $crate::params::ParamValue for $t {
            fn to_f32(self) -> f32 {
                self as u8 as f32
            }
            fn from_f32(v: f32) -> Self {
                <$t>::from_index(v.round().max(0.0) as usize)
            }
        }
    };
}

/// A struct with a flat parameter table (generated by [`param_table!`]).
pub trait Params: Copy + Default + 'static {
    type Id: Copy + Eq + core::fmt::Debug + 'static;
    const ALL: &'static [Self::Id];
    fn param_name(id: Self::Id) -> &'static str;
    fn param_kind(id: Self::Id) -> ParamKind;
    fn param_from_name(name: &str) -> Option<Self::Id>;
    fn get_param(&self, id: Self::Id) -> f32;
    /// Values are clamped to the parameter's range; non-finite values are ignored.
    fn set_param(&mut self, id: Self::Id, value: f32);
}

/// Generate a parameter id enum and `get`/`set` implementation for a struct.
///
/// ```ignore
/// param_table! {
///     /// docs for the enum
///     MyParamId for MyParams {
///         Gain => "master/gain", ParamKind::Float { min: 0.0, max: 2.0, step: 0.001 }, (gain);
///         Wave => "osc/wave", ParamKind::Enum(&Waveform::NAMES), (osc.wave);
///     }
/// }
/// ```
macro_rules! param_table {
    ($(#[$meta:meta])* $id_ty:ident for $target:ty {
        $( $id:ident => $name:literal, $kind:expr, ( $($path:tt)+ ) ; )*
    }) => {
        $(#[$meta])*
        #[derive(Clone, Copy, Debug, PartialEq, Eq, Hash)]
        #[repr(u16)]
        pub enum $id_ty { $( $id, )* }

        impl $id_ty {
            pub const ALL: &'static [$id_ty] = &[ $( $id_ty::$id, )* ];

            /// Stable, slash separated name, e.g. `"filter/cutoff_hz"`.
            pub fn name(self) -> &'static str {
                match self { $( $id_ty::$id => $name, )* }
            }

            pub fn kind(self) -> $crate::params::ParamKind {
                match self { $( $id_ty::$id => $kind, )* }
            }

            pub fn from_name(name: &str) -> Option<$id_ty> {
                match name { $( $name => Some($id_ty::$id), )* _ => None }
            }

            pub fn from_index(i: usize) -> Option<$id_ty> {
                Self::ALL.get(i).copied()
            }
        }

        impl $target {
            pub fn get(&self, id: $id_ty) -> f32 {
                match id { $( $id_ty::$id => $crate::params::ParamValue::to_f32(self.$($path)+), )* }
            }

            /// Set a parameter; the value is clamped to the parameter's valid range.
            pub fn set(&mut self, id: $id_ty, value: f32) {
                let value = if value.is_finite() { id.kind().clamp(value) } else { self.get(id) };
                match id { $( $id_ty::$id => self.$($path)+ = $crate::params::ParamValue::from_f32(value), )* }
            }
        }

        impl $crate::params::Params for $target {
            type Id = $id_ty;
            const ALL: &'static [$id_ty] = $id_ty::ALL;
            fn param_name(id: $id_ty) -> &'static str { id.name() }
            fn param_kind(id: $id_ty) -> $crate::params::ParamKind { id.kind() }
            fn param_from_name(name: &str) -> Option<$id_ty> { $id_ty::from_name(name) }
            fn get_param(&self, id: $id_ty) -> f32 { self.get(id) }
            fn set_param(&mut self, id: $id_ty, value: f32) { self.set(id, value) }
        }
    };
}
